# Generated by Django 6.0 on 2026-04-28 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_income_delete_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='sources',
            new_name='source',
        ),
    ]
